name: Python CI

on:
  push:
    branches:
      - main  # รัน workflow เมื่อมีการ push ไปที่ branch 'main'
  pull_request:
    branches:
      - main  # รัน workflow เมื่อมีการ pull request ไปที่ branch 'main'

jobs:
  test:
    runs-on: ubuntu-latest  # ใช้ environment Ubuntu

    steps:
    # 1. Checkout โค้ดใน repository
    - name: Checkout code
      uses: actions/checkout@v2

    # 2. ตั้งค่า Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # เลือก Python version ที่ต้องการใช้

    # 3. ติดตั้ง dependencies (เช่น pytest หรือ libraries อื่นๆ ที่จำเป็น)
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # ติดตั้ง dependencies จากไฟล์ requirements.txt

    # 4. รันการทดสอบ
    - name: Run tests
      run: |
        python -m unittest discover  # ใช้ unittest เพื่อรันการทดสอบทั้งหมด
